In [1]:
# import required libraries

import torch
import torch.nn as nn
import torch.optim as optim

In [2]:
from sklearn.datasets import load_iris

iris = load_iris()
x = iris.data
y = iris.target

In [3]:
print(x.dtype)
print(y.dtype)
print(x.shape)
print(y.shape)

float64
int32
(150, 4)
(150,)


In [4]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
x.shape

(150, 4)

In [9]:
print(y)
print(y.shape)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
(150,)


In [7]:
import numpy as np
print(np.unique(y)) 
print(len(np.unique(y)))         # model  output의 갯수

[0 1 2]
3


In [8]:
print(x[0])
print(y[0])

[5.1 3.5 1.4 0.2]
0


In [11]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

print(x_train.shape)
print(y_train.shape)

print(x_test.shape)
print(y_test.shape)

(120, 4)
(120,)
(30, 4)
(30,)


In [12]:
from torch.utils.data import DataLoader, Dataset, TensorDataset

class custom_data(Dataset):
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def norm(self, x, m = (5.843, 3.057, 3.758, 1.199), std=(0.825, 0.434, 1.759, 0.15)):
        return (x-m)/std

    def __len__(self):
        return len(self.x)

    def __getitem__(self, index):
        x = self.x[index]
        y = self.y[index]

        x = self.norm(x)

        x = torch.tensor(x, dtype = torch.float32)
        y = torch.tensor(y, dtype = torch.long)

        return x, y
    

In [13]:
train_dataset = custom_data(x_train, y_train)
train_loader = DataLoader(train_dataset, batch_size = 64, shuffle = True)

test_dataset = custom_data(x_test, y_test)
test_loader = DataLoader(test_dataset, batch_size = 64, shuffle = True)

In [14]:
x_in, y_out = next(iter(train_loader))

print(x_in.shape)
print(y_out.shape)

print(x_in.dtype)
print(y_out.dtype)

torch.Size([64, 4])
torch.Size([64])
torch.float32
torch.int64


In [15]:
# make a model
# class:
# inhabit model (torch)
# essential func. 
#           def __init__ -> super().__init__ 
#           def forward

In [16]:
# feature : 4
# num of output : 3 

In [17]:
class Mymodel(nn.Module):
    def __init__(self):
        super(Mymodel, self).__init__()
        self.f1 = nn.Linear(4, 100)
        self.f2 = nn.Linear(100, 3)
        self.act = nn.Sigmoid()

    def forward(self, x):              # x = input
        out = self.f1(x)
        out = self.act(out)
        out = self.f2(out)

        return out
        

In [18]:
"""
model = Mymodel()

from torchsummary import summary
summary(model, (1, 4), device='CPU')
"""

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1               [-1, 1, 100]             500
           Sigmoid-2               [-1, 1, 100]               0
            Linear-3                 [-1, 1, 3]             303
Total params: 803
Trainable params: 803
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
----------------------------------------------------------------


In [19]:
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr = 0.001)

In [20]:
#from tqdm import tqdm

num_epochs = 1000

for epoch in range(num_epochs):
    for x_batch, y_batch in train_loader:
        outputs = model(x_batch)             # 1. prediction

        optimizer.zero_grad()                # 2. init optim
        loss = criterion(outputs, y_batch)   # 3. calculate loss
        loss.backward()                      # 4. calculate gradient
        optimizer.step()                     # 5. update the model

    if (epoch+1) % 100 == 0:
        print(f'Epoch {epoch+1}, Loss: {loss.item()}')

Epoch 100, Loss: 0.7902780771255493
Epoch 200, Loss: 0.6797584891319275
Epoch 300, Loss: 0.5680293440818787
Epoch 400, Loss: 0.5185348987579346
Epoch 500, Loss: 0.47333306074142456
Epoch 600, Loss: 0.42443719506263733
Epoch 700, Loss: 0.3867199420928955
Epoch 800, Loss: 0.39113280177116394
Epoch 900, Loss: 0.3602716028690338
Epoch 1000, Loss: 0.3767527937889099


In [21]:
model.eval()
with torch.no_grad():
    correct = 0
    total = 0
    for x_batch, y_batch in test_loader:
        outputs = model(x_batch)
        # 
        _, predicted = torch.max(outputs.data, 1)
        total += y_batch.size(0)
        correct += (predicted == y_batch).sum().item()      # predict와 y_batch가 같을때 적중률

print(f'Accuracy : {100 * correct / total}%')

Accuracy : 93.33333333333333%
